### ISSUE TITLE
Thousands of "Cannot read property `get` of undefined" errors

### ISSUE THREAD

**Issue by jayporta** [google/recaptcha#449]
**Issue description**
At work we're seeing thousands of errors reported through Sentry that say "Cannot read property `get` of undefined"

**Environment**

 * OS name and version: Windows and Mac
 * PHP version: N/A
 * Web server name and version: Which web server?
 * `google/recaptcha` version: Latest as served by https://www.recaptcha.net/recaptcha/api.js
 * Browser name and version:

56.70% | Chrome 89.0.4389
14.43% | Chrome 75.0.3770
7.22% | Chrome 86.0.4240
6.19% | Sogou Explorer 1.0
3.09% | Chrome 78.0.3904
3.09% | Chrome 88.0.4324
3.09% | Chrome 81.0.4044
2.06% | Chrome 85.0.4183
1.03% | Chrome 79.0.3945
1.03% | Chrome 91.0.4442
1.03% | Chrome 80.0.3987
1.03% | Chrome 87.0.4280

**Reproducing the issue**
All of the error messages are like the following, but sometimes it's k.get, j.get, etc.

TypeError: Cannot read property 'get' of undefined
arguments: [{"message":"Cannot read property 'get' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'get' of undefined\n    at Array.<anonymous> (https://www.gstatic.com/recaptcha/releases/bfvuz6tShG5aoZp4K4zPVf5t/recaptcha__zh_tw.js:106:312)\n    at https://www.gstatic.com/recaptcha/releases/bfvuz6tShG5aoZp4K4zPVf5t/recaptcha__zh_tw.js:215:83\n    at t.<anonymous> (https://cdn.greenxtrade.com/assets/gxportal/2912/js/chunk-vendors.539aec80.js:92:70739)\n    at u (https://cdn.greenxtrade.com/assets/gxportal/2912/js/chunk-vendors.539aec80.js:92:70342)\n    at Object.next (https://cdn.greenxtrade.com/assets/gxportal/2912/js/chunk-vendors.539aec80.js:92:69637)\n    at https://cdn.greenxtrade.com/assets/gxportal/2912/js/chunk-vendors.539aec80.js:92:69337\n    at new Promise (<anonymous>)\n    at r (https://cdn.greenxtrade.com/assets/gxportal/2912/js/chunk-vendors.539aec80.js:92:69130)\n    at t.execute (https://cdn.greenxtrade.com/assets/gxportal/2912/js/chunk-vendors.539aec80.js:92:70655)\n    at https://cdn.greenxtrade.com/assets/gxportal/2912/js/chunk-vendors.539aec80.js:54:100350\n    at u (https://cdn.greenxtrade.com/assets/gxportal/2912/js/chunk-vendors.539aec80.js:54:99822)\n    at Object.next (https://cdn.greenxtrade.com/assets/gxportal/2912/js/chunk-vendors.539aec80.js:54:99117)\n    at https://cdn.greenxtrade.com/assets/gxportal/2912/js/chunk-vendors.539aec80.js:54:98817\n    at new Promise (<anonymous>)\n    at r (https://cdn.greenxtrade.com/assets/gxportal/2912/js/chunk-vendors.539aec80.js:54:98610)\n    at o.initializeReCaptcha.then.t.$recaptcha (https://cdn.greenxtrade.com/assets/gxportal/2912/js/chunk-vendors.539aec80.js:54:100282)\n    at a.<anonymous> (https://cdn.greenxtrade.com/assets/gxportal/2912/js/chunk-79d5d5bf.3402c51e.js:1:77681)\n    at w (https://cdn.greenxtrade.com/assets/gxportal/2912/js/chunk-vendors.539aec80.js:59:50702)\n    at Generator._invoke (https://cdn.greenxtrade.com/assets/gxportal/2912/js/chunk-vendors.539aec80.js:59:51836)\n    at Generator.O.forEach.t.<computed> [as next] (https://cdn.greenxtrade.com/asse..."}]
  
  ***User steps***
Unfortunately I cannot provide this information. I work for a private SAAS company.

**Comment by qhu91it** [comment]
I having similar errors too, for me it it's happen for some user and for all browser
For chromium, error is
```
Uncaught TypeError: Cannot read property 'get' of undefined
    at Array.<anonymous> (recaptcha__en.js:formatted:2149)
    at recaptcha__en.js:formatted:5794
```
For firefox, the error message is difference
```
Uncaught TypeError: K is undefined
    B https://www.gstatic.com/recaptcha/releases/npGaewopg1UaB8CNtYfx-y1j/recaptcha__en.js:96
    l https://www.gstatic.com/recaptcha/releases/npGaewopg1UaB8CNtYfx-y1j/recaptcha__en.js:251
    start {my_website}/js/gg-recaptcha.js?v=ocbDaVYLtLn5U4sEPX_QlVIi9Bv4Bu-5GSHxwjSMDMY:84

```
For IE11
```
SCRIPT5007: Unable to get property 'get' of undefined or null reference
recaptcha__en.js (168,31)
```

I try `CTRL + F5` for few times and this error is gone.

For more infomation, I implement v3 and V2 invisible in same page, load js like this

```
<script src="https://www.recaptcha.net/recaptcha/api.js?onload=recaptchaV2Onload&render=explicit" async defer></script>
<script src="https://www.recaptcha.net/recaptcha/api.js?onload=recaptchaV3Onload&render=@siteKeyV3"></script>
```
