### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined ('key') at Array.<anonymous> (recaptcha__en.js:143:196)

### ISSUE THREAD

**Issue by temrb** [google/recaptcha#505]
Only calling executeRecaptcha on Submit form,
Get this error sometime on page refresh OR page load. Very annoying for UX. 

How do I solve this issue??

Framework: Next.js

Console stack trace: 
```
at Array.<anonymous> (recaptcha__en.js:143:196)
    at recaptcha__en.js:289:485
    at eval (react-google-recaptcha-v3.esm.js?e46a:15:4603)
    at _callee$ (search-input.component.tsx?f48d:76:27)
    at tryCatch (runtime.js?ecd4:45:16)
    at Generator.invoke [as _invoke] (runtime.js?ecd4:274:1)
    at prototype.<computed> [as next] (runtime.js?ecd4:97:1)
    at asyncGeneratorStep (asyncToGenerator.js?8d4f:3:1)
    at _next (asyncToGenerator.js?8d4f:25:1)
    at eval (asyncToGenerator.js?8d4f:32:1)
    at new Promise (<anonymous>)
    at eval (asyncToGenerator.js?8d4f:21:1)
    at eval (search-input.component.tsx?f48d:116:5)
    at commitHookEffectListMount (react-dom.development.js?ac89:23049:1)
    at commitPassiveMountOnFiber (react-dom.development.js?ac89:24816:1)
    at commitPassiveMountEffects_complete (react-dom.development.js?ac89:24781:1)
    at commitPassiveMountEffects_begin (react-dom.development.js?ac89:24768:1)
    at commitPassiveMountEffects (react-dom.development.js?ac89:24756:1)
    at flushPassiveEffectsImpl (react-dom.development.js?ac89:26990:1)
    at flushPassiveEffects (react-dom.development.js?ac89:26935:1)
    at eval (react-dom.development.js?ac89:26725:1)
    at workLoop (scheduler.development.js?bcd2:266:1)
    at flushWork (scheduler.development.js?bcd2:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?bcd2:533:1)
(anonymous) @ recaptcha__en.js:143
(anonymous) @ recaptcha__en.js:289
eval @ webpack-internal:///…aptcha-v3.esm.js:27
_callee$ @ webpack-internal:///…t.component.tsx:157
tryCatch @ webpack-internal:///…ntime/runtime.js:45
invoke @ webpack-internal:///…time/runtime.js:274
prototype.<computed> @ webpack-internal:///…ntime/runtime.js:97
asyncGeneratorStep @ webpack-internal:///…yncToGenerator.js:7
_next @ webpack-internal:///…ncToGenerator.js:29
eval @ webpack-internal:///…ncToGenerator.js:36
eval @ webpack-internal:///…ncToGenerator.js:25
eval @ webpack-internal:///…t.component.tsx:231
commitHookEffectListMount @ webpack-internal:///…evelopment.js:23044
commitPassiveMountOnFiber @ webpack-internal:///…evelopment.js:24811
commitPassiveMountEffects_complete @ webpack-internal:///…evelopment.js:24776
commitPassiveMountEffects_begin @ webpack-internal:///…evelopment.js:24763
commitPassiveMountEffects @ webpack-internal:///…evelopment.js:24751
flushPassiveEffectsImpl @ webpack-internal:///…evelopment.js:26985
flushPassiveEffects @ webpack-internal:///…evelopment.js:26930
eval @ webpack-internal:///…evelopment.js:26720
workLoop @ webpack-internal:///….development.js:266
flushWork @ webpack-internal:///….development.js:239
performWorkUntilDeadline @ webpack-internal:///….development.js:533
```

**Comment by rowan-m** [comment]
Repo is just for PHP client issues. This is about the reCAPTCHA service.
