### ISSUE TITLE
Thousands of "Cannot read property get of undefined" errors

### ISSUE THREAD

**Issue by sp0033212000** [google/recaptcha#509]
Issue description
At work we're seeing tons of errors reported through Sentry that say "TypeError: null is not an object (evaluating 'w.style')"

Environment

 - OS name and version: Windows and Mac
 - PHP version: N/A
 - Web server name and version: Which web server?
 - `google/recaptcha` version: Latest as served by https://www.recaptcha.net/recaptcha/api.js
 - Browser name, version and ratio:
 
LINE 12.21.0 | 0.1359%
Chrome 108.0.0 | 0.1359%
Facebook 339.0.0 | 0.1359%
LINE 12.1.0 | 0.1359%
Mobile Safari 15.5 | 0.2717%
LINE 12.20.0 | 0.2717%
Instagram 262.0.0 | 0.1359%
Safari 15.6 | 0.1359%
LINE 11.18.0 | 0.1359%
LINE 12.8.0 | 0.1359%
LINE 12.6.0 | 0.1359%
Mobile Safari 14.0.2 | 0.1359%
Mobile Safari 14.0.3 | 0.1359%
LINE 11.19.1 | 0.1359%
LINE 12.3.0 | 0.4076%
LINE 12.7.0 | 0.1359%
Chrome Mobile iOS 108.0.5359 | 0.2717%
LINE 10.17.0 | 0.1359%
LINE 12.8.1 | 0.4076%
LINE 11.3.0 | 0.1359%
LINE 12.12.0 | 0.6793%
LINE 11.10.0 | 0.1359%
Mobile Safari 15.6.3 | 0.1359%
LINE 12.11.1 | 0.6793%
Instagram 259.0.0 | 0.2717%
LINE 12.4.0 | 1.0870%
Mobile Safari 15.6 | 0.4076%
LINE 12.9.0 | 0.4076%
LINE 12.2.1 | 0.2717%
Facebook 390.0.0 | 0.1359%
LINE 12.17.1 | 2.5815%
Mobile Safari 15.4 | 0.5435%
LINE 12.20.2 | 1.2228%
LINE 11.19.2 | 0.1359%
LINE 12.10.0 | 0.2717%
LINE 12.14.1 | 0.9511%
LINE 12.21.1 | 1.4946%
Mobile Safari 16.0 | 4.2120%
Mobile Safari 15.6.1 | 0.8152%
Instagram 261.0.0 | 0.2717%
LINE 12.15.1 | 0.8152%
Instagram 263.1.0 | 2.0380%
LINE 12.13.0 | 1.3587%
Mobile Safari 16.1 | 6.5217%
LINE 12.16.0 | 1.6304%
LINE 12.18.0 | 2.8533%
LINE 12.19.0 | 7.3370%
Mobile Safari 16.2 | 1.4946%
LINE 12.20.1 | 55.5707%

Reproducing the issue
All error messages happen after POST to `https://identitytoolkit.googleapis.com/v1/accounts:sendVerificationCode?key=xxxxxxxxx`
then get the following errors:

```
TypeError: null is not an object (evaluating 'w.style')
  at ? (/recaptcha/releases/5qcenVbrhOy8zihcc2aHOWD4/recaptcha__zh_tw.js:445:335)
  at ? (/recaptcha/releases/5qcenVbrhOy8zihcc2aHOWD4/recaptcha__zh_tw.js:167:202)
  at ? ([native code])
  at sentryWrapped(../helpers.ts:87:17)
```

User steps
Unfortunately I cannot provide this information. I work for a private SAAS company.

**Comment by rowan-m** [comment]
Repo is just for PHP client issues. This is about the reCAPTCHA service. I'll take a peek at my logs though and see if this is still happening.
