### ISSUE TITLE
Broken JS results in constant Please try Again, audio option doesn't work, no fallback - effectively locked out of site

### ISSUE THREAD

**Issue by apcsb** [google/recaptcha#538]
I am trying to pay something with PayPal (or log into my account to open a ticket) and I get ReCaptcha.
I get the "click all that contains" as well as "click until there are no more pictures like this" (man is tis one ANNOYINGLY SLOW!)
Anyways, I always get "Try again" and the following in the developer logs (see below)

I checked that there are no network issues and nothing is blocked by the client of plugins.

Browser is Google Chrome 117.0.5938.150 (Official Build) (32-bit)

Basically, I am locked out of making an urgent purchase because some piece of JS misbehaves, and there is no fallback.
In the last months I get this excessively often and have a feeling that I am being used as a free AI vision trainer.
What would you call such piece of technology were you in my situation?

It might be PayPal's fault for not catching up with the latest updates, but the piece of technology that's blocking the user is ReCaptcha, so everything flying off the fan in its direction is rightfully deserved for not communicating with user well enough.

>>

Uncaught ReferenceError: _ is not defined
    at app.js:9:3
    at Object.execCb (require.js:29:229)
    at $.check (require.js:18:423)
    at $.<anonymous> (require.js:23:9)
    at require.js:8:70
    at require.js:23:369
    at z (require.js:7:173)
    at $.emit (require.js:23:340)
    at $.check (require.js:19:459)
    at $.<anonymous> (require.js:23:9)
recaptcha__de.js:301 [Report Only] Refused to create a worker from 'https://www.recaptcha.net/recaptcha/enterprise/webworker.js?hl=de&v=MydHw_zggsxIJuhSbyOmPv5R' because it violates the following Content Security Policy directive: "worker-src 'none'".

(anonymous) @ recaptcha__de.js:301
 [Report Only] Refused to create a worker from 'https://www.recaptcha.net/recaptcha/enterprise/webworker.js?hl=de&v=MydHw_zggsxIJuhSbyOmPv5R' because it violates the following Content Security Policy directive: "worker-src 'none'".

(anonymous) @ recaptcha__de.js:301
anchor?ar=1&k=6LeZ6egUAAAAAGwL8CjkDE8dcSw2DtvuVpdwTkwG&co=aHR0cHM6Ly93d3cucGF5cGFsb2JqZWN0cy5jb206NDQz&hl=de&v=MydHw_zggsxIJuhSbyOmPv5R&theme=light&size=normal&cb=p4jzjm4f7zo3:184 [Report Only] Refused to create a worker from 'https://www.recaptcha.net/recaptcha/enterprise/webworker.js?hl=de&v=MydHw_zggsxIJuhSbyOmPv5R' because it violates the following Content Security Policy directive: "worker-src 'none'".

anchor:184 [Report Only] Refused to create a worker from 'https://www.recaptcha.net/recaptcha/enterprise/webworker.js?hl=de&v=MydHw_zggsxIJuhSbyOmPv5R' because it violates the following Content Security Policy directive: "worker-src 'none'".

about:blank:1     Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
about:blank:1     Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
about:blank:1     Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
about:blank:1     Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
3chrome-extension://d….frameInjector.js:1 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at HTMLDocument.a (content.frameInjector.js:1:2792)
content.frameInjector.js:1 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at HTMLDocument.a (content.frameInjector.js:1:2792)
129content.frameInjector.js:1 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at HTMLDocument.a (content.frameInjector.js:1:2792)
7content.frameInjector.js:1 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at HTMLDocument.a (content.frameInjector.js:1:2792)
a @ content.frameInjector.js:1
Show 1 more frame
Show less
recaptcha__de.js:677 XHR finished loading: POST "https://www.recaptcha.net/recaptcha/enterprise/replaceimage?k=6LeZ6egUAAAAAGwL8CjkDE8dcSw2DtvuVpdwTkwG".
O.send @ recaptcha__de.js:677
(anonymous) @ recaptcha__de.js:130
LE.M @ recaptcha__de.js:752
(anonymous) @ recaptcha__de.js:46
O.W1 @ recaptcha__de.js:747
ax.Nz @ recaptcha__de.js:748
ax.send @ recaptcha__de.js:749
(anonymous) @ recaptcha__de.js:753
Promise.then (async)
(anonymous) @ recaptcha__de.js:753
(anonymous) @ recaptcha__de.js:278
lz @ recaptcha__de.js:639
uJ.send @ recaptcha__de.js:752
(anonymous) @ recaptcha__de.js:294
(anonymous) @ recaptcha__de.js:240
(anonymous) @ recaptcha__de.js:206
O.dispatchEvent @ recaptcha__de.js:647
(anonymous) @ recaptcha__de.js:187
H7.Ay @ recaptcha__de.js:909
(anonymous) @ recaptcha__de.js:416
(anonymous) @ recaptcha__de.js:871
(anonymous) @ recaptcha__de.js:206
O.dispatchEvent @ recaptcha__de.js:647
Yf.N @ recaptcha__de.js:714
pE @ recaptcha__de.js:645
w @ recaptcha__de.js:407
r @ recaptcha__de.js:61
6content.frameInjector.js:1 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at HTMLDocument.a (content.frameInjector.js:1:2792)

>>

**Comment by Jorduin** [comment]
Or... hear me out: they could end the project. No more problems.
